- name: variables to print
  hosts: web
  vars: #play level,all tasks in this play have access to this
    COURSE: "DevOps with AWS"
    Duration: "120 hrs"
    Trainer: "SKR"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        #msg: "Hi, i am learing DevOps with AWS,Duration is 120 hrs,Trainer is SKR"
        msg: "Hi, i am learing {{COURSE}},Duration is {{Duration}},Trainer is {{Trainer}}"
    
    - name: print the information again
      vars: # Task level variables
        COURSE: ANSIBLE
      ansible.builtin.debug:
        msg: "Hi,I am learning {{COURSE}}"

     - name: print the information again and agains
      ansible.builtin.debug:
        #msg: "Hi, i am learing DevOps with AWS,Duration is 120 hrs,Trainer is SKR"
        msg: "Hi, i am learing {{COURSE}},Duration is {{Duration}},Trainer is {{Trainer}}"

