  - name: variables from prompt
    hosts: web
    vars_prompt:
    - name: COURSE
      prompt: please enter the course name
    - name: Duration
      prompt: please enter the course duration
    - name: Trainer
      prompt: please enter the trainer name
      private: false
    tasks:
      - name: 
        ansible.builtin.debug:
          msg: "I am learning {{COURSE}} with duration of {{Duration}} and trainer is {{Trainer}}"
     