- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS PLAY LEVEL"
    DURATION: "120HR"
    TRAINER: "SKR"
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  tasks:
  - name: print the information
    vars:
      COURSE: "Devops with AWS TASK LEVEL"
    ansible.builtin.debug:
      msg: "Hi i am learing {{COURSE}}"


     