  - name: variables from prompt
    hosts: web
    vars_prompt:
    - name: COURSE
      prompt: please enter the course name
      private: false
    - name: Duration
      prompt: please enter the course duration
      private: false
    - name: Trainer
      prompt: please enter the trainer name
      private: false
    tasks:
     - name: print the information again
       vars: # Task level variables
        COURSE: ANSIBLE
       ansible.builtin.debug:
        msg: "Hi,I am learning {{COURSE}} task level"
     - name: 
       ansible.builtin.debug:
        msg: "I am learning {{COURSE}}"
     