- name: loops demo
  hosts: web
  become: yes
  tasks:
   - name: print items in loop
     ansible.builtin.package:
      name: "{{ item }}"
      state: present
     loop:
     - nginx
     - mysql
     - postfix
     - httpd

