- name: Demo on function/filters
  hosts: web
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ Course | default('Ansible') }}"

    - name: conver to uppercase
      vars:
        greeting: "Hello ram"
      ansible.builtin.debug:
        msg: " {{ greeting | upper }} "