- name: Demo on function/filters
  hosts: web
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: "Hello {{ Course | default('Ansible') }}"

    - name: convert to uppercase
      vars:
        greeting: "Hello ram"
      ansible.builtin.debug:
        msg: " {{ greeting | upper }} "
    
    - name: convert to lowercase
      vars:
        greeting: "Hello ram"
      ansible.builtin.debug:
        msg: "{{ greeting | lower }}"
    
    - name: Get the unique number
      vars:
        numbers: [1,3,55,6,7,1,3]
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

    - name: Get max and min
      vars:
        numbers: [1,2,3,6,3]
      ansible.builtin.debug:
        msg: "{{  numbers | max , numbers | min }}"